### ISSUE TITLE
When adding a new layer, the no data value is not saved

### ISSUE THREAD

**Issue by sgiaccio** [slms4redd/admin-interface#62]

**Comment by Damianofds** [comment]
is your build made after this commit
https://github.com/slms4redd/admin-interface/commit/8ee1d51aa2cb011861bbec8a689f795ec9e7423a
?

2015-06-23 16:16 GMT+02:00 sgiaccio <notifications@github.com>:

**Comment by sgiaccio** [comment]
It works with the last build, closing it.
