### ISSUE TITLE
"Attribute name" and "No-data value" fields are not correctly handled when editing or creating a layer

### ISSUE THREAD

**Issue by sgiaccio** [slms4redd/admin-interface#63]

**Comment by Damianofds** [comment]
is your build made after this commit
https://github.com/slms4redd/admin-interface/commit/8ee1d51aa2cb011861bbec8a689f795ec9e7423a
?

2015-06-23 16:18 GMT+02:00 sgiaccio <notifications@github.com>:

**Comment by sgiaccio** [comment]
no, I was using an older build, closing it
